require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'bower_components/**/*'
    - 'Guardfile'
  RunRailsCops: true

# Disable for Rake tasks
Lint/HandleExceptions:
  Enabled: false

Style/Documentation:
  Enabled: false

# Prevent "Use nested module/class definitions instead of compact style."
Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 12

# Enabled disabled Cops
Style/CollectionMethods:
  Enabled: true

# Do not enforce Hash Style for now
Style/SpaceInsideHashLiteralBraces:
  Enabled: false
